name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda and create env
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: schiff-base-ml
          auto-activate-base: false

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: pytest
